name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Go App Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/goapp:latest -f landlord/Dockerfile .

      - name: Build Postgres Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/postgres-custom:latest -f landlord/postgres.Dockerfile .

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/goapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres-custom:latest
