name: Build and Push Docker Images

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ "main" ]  # Or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vishalreddy11
          password: Vr117569tk1.

      - name: Build Go App Docker Image
        run: |
          docker build -t vishalreddy11/goapp:latest -f landlord/Dockerfile .

      - name: Build Postgres Docker Image
        run: |
          docker build -t vishalreddy11/postgres-custom:latest -f landlord/postgres.Dockerfile .

      - name: Push Docker Images
        run: |
          docker push vishalreddy11/goapp:latest
          docker push vishalreddy11/postgres-custom:latest
